name: CI
on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2019.4.13f1

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          lfs: true

      - uses: actions/cache@v2.1.2
        with:
          path: Library
          key: Library   

      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1.3
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Unity - Builder
        uses: webbertakken/unity-builder@v2.0-aplha-5

        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: Android
      # Output
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: Build
          path: build